name: laratasker
recipe: laravel
config:
  webroot: public

services:
  appserver:
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_23.x | bash -
      - apt-get install -y nodejs
      - apt-get install -y chromium
      - apt-get install -y libatk1.0-0 libatk-bridge2.0-0 libcups2 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libasound2 libpangocairo-1.0-0 libpango-1.0-0 libgtk-3-0 libnss3
    ports:
      - '24690:24690'
      - '24691:24691'
      - '24692:24692'

  database:
    type: mysql:8.0
    creds:
      user: laravel
      password: laravel
      database: laravel

  pma:
    type: phpmyadmin
    hosts:
      - database

  adminer:
    type: compose
    services:
      image: dehy/adminer
      command: /bin/s6-svscan /etc/services.d
      ports:
        - 80

tooling:
  php:
    service: appserver
    description: Run php commands
    cmd: php
  npm:
    service: appserver
    description: Run npm commands
    cmd: npm
  artisan:
    service: appserver
    description: Run artisan commands
    cmd: php artisan
  composer:
    service: appserver
    description: Run composer commands
    cmd: composer

proxy:
  appserver: [ laratasker.lndo.site ]
  pma: [ pma.laratasker.lndo.site ]
  adminer: [ adminer.laratasker.lndo.site ]